version: '3.9'

services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    networks:
      - ${NETWORK_DB}

networks:
  ${NETWORK_DB}:
    name: ${NETWORK_DB}